### ISSUE TITLE
runapi中报错，请问大佬是什么原因啊，谢谢大佬

### ISSUE THREAD

**Issue by djhdj1** [wangziyingwen/AutoApiP#1]
runapi.py:84: SyntaxWarning: name 'access_token_list' is assigned to before global declaration
  global access_token_list
Traceback (most recent call last):
  File "runapi.py", line 9, in <module>
    access_token_list=['wangziyingwen']*int(app_num)
ValueError: invalid literal for int() with base 10: ''
Error: Process completed with exit code 1.

**Comment by wangziyingwen** [comment]
你APP_NUM输入了啥？

**Comment by wangziyingwen** [comment]
你把两个py脚本改一下
runapi.py第7行，updatetoken.py第9行
都有一个   if app_num == None:
改成  if app_num == '':
也就是把None改成''  [（英文单引号，里面没东西）]
8好意思
 ![image](https://s3.ax1x.com/2021/01/09/sQnAtf.png)

**Comment by djhdj1** [comment]
好用了，谢谢大佬
