### ISSUE TITLE
auto api pro和Update Token运行报错

### ISSUE THREAD

**Issue by 12123ads** [wangziyingwen/AutoApiP#2]
auto api pro报错是
Run python runapi.py
Traceback (most recent call last):
  File "runapi.py", line 88, in <module>
    access_token_list[a-1]=getmstoken(ms_token)
  File "runapi.py", line 60, in getmstoken
    refresh_token = jsontxt['refresh_token']
KeyError: 'refresh_token'
Error: Process completed with exit code 1.

Update Token报错是
Run python runapi.py
Traceback (most recent call last):
  File "runapi.py", line 88, in <module>
    access_token_list[a-1]=getmstoken(ms_token)
  File "runapi.py", line 60, in getmstoken
    refresh_token = jsontxt['refresh_token']
KeyError: 'refresh_token'
Error: Process completed with exit code 1.
大佬看看这个咋办qaq

**Comment by wangziyingwen** [comment]
微软密钥错了啊。再获取一次换掉，注意开有结尾不要双引号空格空行

**Comment by 12123ads** [comment]
好的

**Comment by 12123ads** [comment]
好的谢谢


---原始邮件---
发件人: &quot;wangziyingwen&quot;<notifications@github.com&gt;
发送时间: 2021年1月10日(周日) 晚上8:01
收件人: &quot;wangziyingwen/AutoApiP&quot;<AutoApiP@noreply.github.com&gt;;
抄送: &quot;Author&quot;<author@noreply.github.com&gt;;&quot;12123ads&quot;<3127086580@qq.com&gt;;
主题: Re: [wangziyingwen/AutoApiP] auto api pro和Update Token运行报错 (#2)




 
微软密钥错了啊。再获取一次换掉，注意开有结尾不要双引号空格空行
 
&mdash;
