### ISSUE TITLE
run-api日志里数字变成*

### ISSUE THREAD

**Issue by GreenTeodoro839** [wangziyingwen/AutoApiP#4]
每次运行都有一些数字莫名其妙显示*，甚至有时候账号序号也是*

**Comment by wangziyingwen** [comment]
这个就是因为账号数造成的。github为了防止泄密，会把符合secret里内容的东西都隐藏掉。账号数是2，*号就代表2，没有什么大碍

**Comment by GreenTeodoro839** [comment]
谢谢，我还以为出bug了
