### ISSUE TITLE
自动运行不更新token

### ISSUE THREAD

**Issue by SKSK-2** [wangziyingwen/AutoApiP#5]
![Snipaste_2021-01-20_22-22-42](https://user-images.githubusercontent.com/77012422/105188489-ec110280-5b6e-11eb-853e-9905c510211d.jpg)
自动运行的时候token不更新啊
手动触发的时候才能跟着运行
全程照着步骤有查了一下没发现有问题
请问是我有什么步骤没注意吗

**Comment by SKSK-2** [comment]
如图，正在运行是我手动触发的，下两行是自动运行的token就没有更新，再下面是配置好之后试运行的

**Comment by wangziyingwen** [comment]
token更新我设置了一周更3次而已。不用更太频繁，token有效期挺久的

**Comment by SKSK-2** [comment]
> ![Snipaste_2021-01-20_22-22-42](https://user-images.githubusercontent.com/77012422/105188489-ec110280-5b6e-11eb-853e-9905c510211d.jpg)
> 自动运行的时候token不更新啊
> 手动触发的时候才能跟着运行
> 全程照着步骤有查了一下没发现有问题
> 请问是我有什么步骤没注意吗

1
