### ISSUE TITLE
之前的还可以用吗

### ISSUE THREAD

**Issue by Nikeguo** [wangziyingwen/AutoApiP#6]
AutoApiSecret-加密版
我用的还是你的这个项目，需要再按你的教程再做一次吗？我现在的只有13天就到期了，挂‘AutoApiSecret-加密版’
好几个月了

**Comment by wangziyingwen** [comment]
续期相关请看常见错误。
项目大同小异，只是增加了写随机参数跟优化，换不换无所谓

**Comment by Nikeguo** [comment]
谢谢，今天刚刚续费成功------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;wangziyingwen&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年1月22日(星期五) 下午4:04
收件人:&nbsp;&quot;wangziyingwen/AutoApiP&quot;<AutoApiP@noreply.github.com&gt;;
抄送:&nbsp;&quot;郭柯廷&quot;<1667623488@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [wangziyingwen/AutoApiP] 之前的还可以用吗 (#6)
